### ISSUE TITLE
Feedback and Feature Requests

### ISSUE THREAD

**Issue by Buttars** [dawiidio/pli#1]
Hey man, this looks like a really cool idea. Was this inspired by the Angular CLI or similar?

Personally I don't like way variables are referenced in file names and such. I'd much prefer the approach Angular has which provides a file tree like structure and programmatically manipulate it instead of relying on template variable references alone.

For file names they use double underscores __ and <% ... %> for templating.
 
It would make much more sense to adopt the same semantic syntax and general language they've set since it works and is a familiar pattern to anyone who's worked with Angular schematics. Don't need to reinvent the wheel here imho. Personal preference but I see the Angular Schematic standard as a much cleaner implementation.

An additional feature could be added to allow the schematic to redefine the syntax to avoid conflicts across languages. But for a standard I think the one listed above is a great start.

Here is an example of an Angular Schematic that has a file name that references a variable as well as demonstrating the value of having programmatic templating where the template actually references a function provided by the schematic. In this example it allows for several transformations which I see as absolutely necessary.

https://github.com/ViktorSlavov/schematic-component-example/blob/master/src/component/files/card/__name%40dasherize__.component.ts.template

Here is a great overview of Angular Schematics and how they are implemented: https://javascript-conference.com/wp-content/uploads/2020/11/Angular_Schematics_%E2%80%93_The_Solution_to_All_Your_Problems.pdf

A few feature requests:
- Support a standard templating syntax
- Support programmatic references to properties, functions, etc., from schematics in templates
- Support upgrades and migrations
- Schematics define required build/run tools and have ways to automatically install them per platform as defined in the schematic

I'm more than happy to help implement these things if you share the idea. Great start on this project, I could see this becoming very popular if done correctly. 😄

**Comment by dawiidio** [comment]
Hey! Thanks for your input and very detailed description. The main idea for Pli came from Nest.js cli, but sure we can say Angular since Nest.js was inspired by Angular.

Regarding files, and let's say "virtual tree", I see some pluses of it but it also determines that we need a config file to define such a structure. I wouldn't want to force users to have config file because the whole idea was based on ability to fast start just with template files.

Nevertheless, you also mentioned the ability to call functions from template, like eg `<% uppercase($TEST$) %>`. I considered it, but decided to go with just variables for simplicity on the beginning. For now you can achieve the same results by piping variable in config file to transform it's value, like that:

```ts
new TemplateVariable({
    name: 'TEST'
}).pipe(
    (value: string) => value.toUpperCase(),
    (value: string) => underscore(value),
    // ...
);
```

And tbh I like the idea because of encapsulation: you can keep transformers of the variable close to it. But I am open to the possibility of allowing to do the same on template level. I'm not sure about the syntax, I know you mentioned the angular one but I was thinking more of something like that `$TEST:uppercase:underscore$`.

And to answer points about the features:

1. I don't want to turn Pli into Angular Cli. I like the idea of Angular Cli, it was the inspiration behind Pli but here it ends. I want Pli to be more flexible and to be able to run as zero-config. Only if someone want's to extend the functionality or create more complex templates should be able to create config and do more stuff there.
2. I'm in, but probably with syntax other than Angular's one
3. Tbh I don't see the need for migrations for now - KISS principle 😃 
4. - || -

But if you still wanna help then I was thinking of introducing some new features in the near future, like:

1. new type of interaction with files - I want to add ability to modify existing files, so for example: you could add exports to the index for newly created components
2. opening the event system to user, so that the user can plug in into the system
3. and as you mentioned before the ability to call transformers from template is also worth of considering
4. ability to run templates from url/repo
